name: churn_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - Flask==3.0.0
    - gunicorn==21.2.0
    - Werkzeug==3.0.1
    - pandas==2.1.4
    - numpy==1.26.2
    - scikit-learn==1.3.2
    - matplotlib==3.8.2
    - joblib==1.3.2
    - shap==0.44.0
    - lifelines==0.27.8
    - scipy==1.11.4
